stages:
  - build
  - test
  - deploy

build:
  stage: build
  image: maven:3.6.3-jdk-11
  script:
    - mvn clean package -Dmaven.test.skip=true
    - docker build -t $DOCKER_REGISTRY/spring-petclinic:latest .
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD $DOCKER_REGISTRY
    - docker push $DOCKER_REGISTRY/spring-petclinic:latest

test:
  stage: test
  image: openjdk:11-jre-slim
  script:
    - docker pull $DOCKER_REGISTRY/spring-petclinic:latest
    - docker run --rm -p 8080:8080 $DOCKER_REGISTRY/spring-petclinic:latest

deploy:
  stage: deploy
  image: alpine:latest
  script:
    - apk add --update curl
    - curl --request POST --header "Content-Type: application/json" --data '{"content":"Deploying Spring PetClinic..."}' $DISCORD_WEBHOOK_URL

