image: docker:latest

services:
  - docker:dind

stages:
  - build
  - test
  - release
  - deploy

build:
  stage: build
  script:
    - docker build -t $DOCKER_REGISTRY/spring-petclinic .
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD $DOCKER_REGISTRY
    - docker tag spring-petclinic $DOCKER_USERNAME/spring-petclinic
    - docker push $DOCKER_USERNAME/spring-petclinic:latest
  

test:
  stage: test
  script:
    - docker run --rm -d -it $DOCKER_USERNAME/spring-petclinic:latest mvn clean verify
  
release:
  stage: release
  script:
    - docker build -t $CI_REGISTRY_IMAGE/spring-petclinic .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE/spring-petclinic:latest
  
deploy:
  stage: deploy
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE/spring-petclinic:latest
    - docker run -d -it -p 8080:8080 $CI_REGISTRY_IMAGE/spring-petclinic:latest

